INSERT INTO gomax_database.Film (title,runtime,genre,plot,actors,poster) VALUES
('The Gentlemen','113 min','Action, Crime','A British drug lord tries to sell off his highly profitable empire to a dynasty of Oklahoma billionaires.','Matthew McConaughey, Charlie Hunnam, Michelle Dockery, Jeremy Strong','https://m.media-amazon.com/images/M/MV5BMTlkMmVmYjktYTc2NC00ZGZjLWEyOWUtMjc2MDMwMjQwOTA5XkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_SX300.jpg'),
('Dolittle','101 min','Action, Adventure, Comedy, Family, Fantasy','A physician discovers that he can talk to animals.','Robert Downey Jr., Antonio Banderas, Michael Sheen, Jim Broadbent','https://m.media-amazon.com/images/M/MV5BMDNkODA5ZGQtODczOS00OTQxLThhMTItMjk0ZmNhMDM0YjNmXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg'),
('Les Misérables','102 min','Crime, Drama, Thriller','A cop of provinces moves Paris to join the Anti-Crime Brigade of Montfermeil, discovering an underworld where the tensions between the different groups mark the rhythm.','Damien Bonnard, Alexis Manenti, Djibril Zonga, Issa Perica','https://m.media-amazon.com/images/M/MV5BZTZkYTBkY2MtMzRmNS00NjM3LWFiMzItZmJjNzNhMjgyYzczXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg'),
('1917','119 min','Drama, War','April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.','Dean-Charles Chapman, George MacKay, Daniel Mays, Colin Firth','https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_SX300.jpg'),
('Jumanji','104 min','Adventure, Comedy, Family, Fantasy','After being trapped in a jungle board game for 26 years, a Man-Child wins his release from the game. But, no sooner has he arrived that he is forced to play again, and this time sets the creatures of the jungle loose on the city. Now it is up to him to stop them.','Robin Williams, Jonathan Hyde, Kirsten Dunst, Bradley Pierce','https://m.media-amazon.com/images/M/MV5BZTk2ZmUwYmEtNTcwZS00YmMyLWFkYjMtNTRmZDA3YWExMjc2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg'),
('Joker','122 min','Crime, Drama, Thriller','In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.','Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy','https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg'),
('Bad Boys for Life','124 min','Action, Comedy, Crime, Thriller','The Bad Boys Mike Lowrey and Marcus Burnett are back together for one last ride in the highly anticipated Bad Boys for Life.','Will Smith, Martin Lawrence, Vanessa Hudgens, Alexander Ludwig','https://m.media-amazon.com/images/M/MV5BMWU0MGYwZWQtMzcwYS00NWVhLTlkZTAtYWVjOTYwZTBhZTBiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg'),
('Sonic the Hedgehog','99 min','Action, Adventure, Family, Sci-Fi','After discovering a small, blue, fast hedgehog, a small-town police officer must help it defeat an evil genius who wants to do experiments on it.','Ben Schwartz, Tika Sumpter, Jim Carrey, James Marsden','https://m.media-amazon.com/images/M/MV5BNDc1ZTlmOWUtNDY2YS00OGU5LTg2MTYtYTk2MmQzMGE2NzUwXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg'),
('Spies in Disguise','102 min','Animation, Action, Adventure, Comedy, Family, Sci-Fi','When the world''s best spy is turned into a pigeon, he must rely on his nerdy tech officer to save the world.','Rachel Brosnahan, Jarrett Bruno, Claire Crosby, Toru Uchikado','https://m.media-amazon.com/images/M/MV5BNzg1MzM3OWUtNjgzZC00NjMzLWE1NzAtOThiMDgyMjhhZDBhXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg');
